# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generates the GCP Workflows YAML of a workflow definition.

Pure functions (no I/O). The generated YAML:

* passes ``run_id`` / ``step_id`` / ``execution_id`` to every executor call,
  so the executor checkpoints the step and reuses its generation job;
* gates every step with a ``switch`` that skips it when ``<step>_out`` is
  already set from ``prior_outputs`` (resume); downstream references read
  ``<step>_out`` instead of the call result;
* reads ``prior_outputs`` from the execution arguments or, when
  ``fetch_checkpoint`` is set, from ``GET /runs/{run_id}/checkpoint``;
* retries transient failures natively: connection errors, timeouts and
  HTTP 429 / 500 / 502 / 503 / 504, incl. 504 ``STEP_IN_PROGRESS``, unless
  the executor answers ``retry_safe: false``;
* sets an explicit ``timeout`` on every step call (Cloud Run limit);
* reports the outcome to ``POST /runs/{run_id}/finished``. Callback
  failures are swallowed (the reconciler covers missed callbacks).

Executions without ``run_id`` skip the checkpoint and both callbacks.
"""

import hashlib
import json
import re
from collections.abc import Iterable, Iterator, Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any

import yaml
from pydantic import BaseModel

from src.workflows.schema.workflow_model import (
    NodeTypes,
    StepStatusEnum,
    WorkflowBase,
)
from src.workflows.step_state_keys import (
    ITERATION_SEPARATOR,
    group_step_states,
    step_state_key,
    validate_step_id_chars,
)

# First line of every generated source (visible in the GCP console).
YAML_HEADER = "# Generated by Creative Studio. Do not edit.\n"

# Loop ports: back-edge input / output and the per-iteration item output.
LOOP_ENDING = "loop_ending"
LOOP_CURRENT_ITEM = "current_item"
RESOLVE_LOOP_ITEMS_PATH = "resolve-loop-items"

# Retry policy of every executor call.
STEP_MAX_RETRIES = 3
STEP_RETRY_INITIAL_DELAY_SECONDS = 5
STEP_RETRY_MAX_DELAY_SECONDS = 120
STEP_RETRY_MULTIPLIER = 2
TRANSIENT_HTTP_CODES = (429, 500, 502, 503, 504)
TRANSIENT_ERROR_TAGS = (
    "ConnectionError",
    "ConnectionFailedError",
    "TimeoutError",
)
# Checkpoint fetch and callbacks answer quickly.
CALLBACK_TIMEOUT_SECONDS = 60
# Above this size prior outputs are fetched from the checkpoint endpoint
# instead of being passed as execution arguments (Q7).
PRIOR_OUTPUTS_ARGS_MAX_BYTES = 32 * 1024
# GCP Workflows limits.
MAX_ASSIGNMENTS_PER_STEP = 50
MAX_SOURCE_BYTES = 128 * 1024
MAX_STEP_ID_LENGTH = 128
MAX_HTTP_TIMEOUT_SECONDS = 1800
_YAML_LINE_WIDTH = 4096

PREDICATE_NAME = "is_transient"
# Execution arguments set by the backend; user inputs cannot use them.
RESERVED_ARGS = frozenset(
    {"user_auth_header", "run_id", "prior_outputs", "fetch_checkpoint"}
)
# Step ids become YAML variable names (<step>_out / <step>_result).
_STEP_ID_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_IDENTIFIER_RE = _STEP_ID_RE

# GCP Workflows expressions.
_RUN_ID_EXPR = '${default(map.get(args, "run_id"), "")}'
_EXECUTION_ID_EXPR = '${sys.get_env("GOOGLE_CLOUD_WORKFLOW_EXECUTION_ID")}'
_PRIOR_ARGS_EXPR = '${map.get(args, "prior_outputs")}'
_FETCH_CHECKPOINT_EXPR = (
    '${run_id != "" and '
    'default(map.get(args, "fetch_checkpoint"), false) == true}'
)
_CHECKPOINT_PRIOR_EXPR = '${map.get(checkpoint.body, "prior_outputs")}'
_NO_RUN_ID_EXPR = '${run_id == ""}'
# The executor answers retry_safe: false when a retried call could start
# a second generation job (calls without run_id).
_NOT_RETRY_SAFE_EXPR = (
    '${default(map.get(e.body, "retry_safe"), true) == false}'
)


class _NoAliasDumper(yaml.SafeDumper):
    """Safe dumper that never emits YAML anchors / aliases."""

    def ignore_aliases(self, data: Any) -> bool:
        del data  # Never alias, whatever the value.
        return True


@dataclass(frozen=True)
class LoopInfo:
    """A ``Loop`` step and its body.

    Attributes:
        loop_id: Id of the ``Loop`` step.
        end_step_id: Id of the step whose ``loop_ending`` output closes the
            loop (the back-edge target of ``inputs.loop_ending``).
        body: Ids of the steps downstream of the loop, in execution order.
    """

    loop_id: str
    end_step_id: str
    body: tuple[str, ...]


@dataclass(frozen=True)
class WorkflowGraph:
    """Dependency analysis of the steps of a workflow definition.

    Attributes:
        order: Every step, in topological order (stable for ties).
        dependencies: Step id -> ids of the steps it references.
        user_input_ids: Ids of the user-input steps (execution arguments).
        referenced_outputs: Call step id -> its outputs referenced by other
            steps (the only outputs a resumed execution needs).
        loops: Loop step id -> its :class:`LoopInfo`.
        loop_of: Loop body step id -> id of the loop that owns it.
    """

    order: tuple[Any, ...]
    dependencies: Mapping[str, frozenset[str]]
    user_input_ids: frozenset[str]
    referenced_outputs: Mapping[str, frozenset[str]]
    loops: Mapping[str, LoopInfo] = field(default_factory=dict)
    loop_of: Mapping[str, str] = field(default_factory=dict)

    @property
    def call_steps(self) -> tuple[Any, ...]:
        """Steps that call the executor, in execution order."""
        return tuple(
            step
            for step in self.order
            if step.step_id not in self.user_input_ids
        )

    @property
    def top_level_call_steps(self) -> tuple[Any, ...]:
        """Call steps outside loops (not ``Loop`` steps nor loop bodies).

        Only these are gated by (and carried in) ``prior_outputs``.
        """
        return tuple(
            step
            for step in self.call_steps
            if step.step_id not in self.loops
            and step.step_id not in self.loop_of
        )


def _is_user_input(step: Any) -> bool:
    return step.type == NodeTypes.USER_INPUT


def _is_loop(step: Any) -> bool:
    return step.type == NodeTypes.LOOP


def _dump_model(value: Any) -> Any:
    if isinstance(value, BaseModel):
        return value.model_dump()
    return value if value is not None else {}


def _as_reference(value: Any) -> tuple[str, str] | None:
    """``(step, output)`` if ``value`` is a step output reference."""
    if isinstance(value, Mapping):
        step, output = value.get("step"), value.get("output")
        if isinstance(step, str) and isinstance(output, str):
            return step, output
    return None


def _iter_references(value: Any) -> Iterator[tuple[str, str]]:
    reference = _as_reference(value)
    if reference is not None:
        yield reference
    elif isinstance(value, Mapping):
        for item in value.values():
            yield from _iter_references(item)
    elif isinstance(value, (list, tuple)):
        for item in value:
            yield from _iter_references(item)


def _step_references(step: Any) -> list[tuple[str, str]]:
    """Forward data references of ``step``.

    ``inputs.loop_ending`` of a ``Loop`` step is a loop-closing back-edge,
    not a data dependency: it is excluded (see :func:`_loop_ending_ref`).
    """
    inputs = _dump_model(step.inputs)
    references: list[tuple[str, str]] = []
    for name, value in inputs.items():
        if _is_loop(step) and name == LOOP_ENDING:
            continue
        references.extend(_iter_references(value))
    return references


def _loop_ending_ref(step: Any) -> tuple[str, str] | None:
    """Back-edge ``(step, output)`` of a ``Loop`` step's ``loop_ending``."""
    return _as_reference(_dump_model(step.inputs).get(LOOP_ENDING))


def _topological_order(
    steps: Sequence[Any], dependencies: Mapping[str, frozenset[str]]
) -> tuple[Any, ...]:
    """Kahn's algorithm; ties keep the definition order.

    ``dependencies`` holds forward edges only (loop back-edges excluded).
    """
    steps_by_id = {step.step_id: step for step in steps}
    dependents: dict[str, list[str]] = {step_id: [] for step_id in steps_by_id}
    in_degree = {step_id: len(deps) for step_id, deps in dependencies.items()}
    for step in steps:
        for dependency in dependencies[step.step_id]:
            dependents[dependency].append(step.step_id)
    queue = [step.step_id for step in steps if in_degree[step.step_id] == 0]
    order = []
    while queue:
        current = queue.pop(0)
        order.append(steps_by_id[current])
        for dependent in dependents[current]:
            in_degree[dependent] -= 1
            if in_degree[dependent] == 0:
                queue.append(dependent)
    if len(order) != len(steps):
        raise ValueError("Cycle detected in workflow graph")
    return tuple(order)


def _descendants(
    start: str, dependencies: Mapping[str, frozenset[str]]
) -> set[str]:
    """Steps that depend (directly or transitively) on ``start``."""
    dependents: dict[str, set[str]] = {
        step_id: set() for step_id in dependencies
    }
    for step_id, deps in dependencies.items():
        for dep in deps:
            dependents.setdefault(dep, set()).add(step_id)
    found: set[str] = set()
    queue = list(dependents.get(start, ()))
    while queue:
        current = queue.pop()
        if current in found:
            continue
        found.add(current)
        queue.extend(dependents.get(current, ()))
    return found


def _analyze_loops(
    steps: Sequence[Any],
    order: Sequence[Any],
    dependencies: Mapping[str, frozenset[str]],
) -> tuple[dict[str, LoopInfo], dict[str, str]]:
    """Validates every ``Loop`` subgraph and returns its body.

    Raises:
        ValueError: Missing or invalid ``loop_ending``, unconnected
            ``current_item``, unreachable loop end, post-loop continuation,
            ``loop_ending`` wired to a non-loop step, nested or overlapping
            loops.
    """
    steps_by_id = {step.step_id: step for step in steps}
    loop_ids = [step.step_id for step in order if _is_loop(step)]
    # Steps whose loop_ending output closes a loop -> that loop.
    loop_end_of: dict[str, str] = {}
    for step in steps:
        for ref_step, ref_output in _step_references(step):
            if ref_output == LOOP_ENDING and ref_step in steps_by_id:
                raise ValueError(
                    f"Step {step.step_id!r}: 'loop_ending' outputs can only "
                    "connect to the 'loop_ending' input of a Loop step"
                )
    for loop_id in loop_ids:
        reference = _loop_ending_ref(steps_by_id[loop_id])
        if (
            reference is None
            or reference[0] not in steps_by_id
            or reference[0] == loop_id
            or reference[1] != LOOP_ENDING
        ):
            raise ValueError(
                f"Loop step {loop_id!r} must have its 'loop_ending' input "
                "connected to the 'loop_ending' output of the last step of "
                "the loop"
            )
        if reference[0] in loop_end_of:
            raise ValueError(
                f"Step {reference[0]!r} cannot end more than one loop"
            )
        loop_end_of[reference[0]] = loop_id

    loops: dict[str, LoopInfo] = {}
    loop_of: dict[str, str] = {}
    for loop_id in loop_ids:
        end_step_id = _loop_ending_ref(steps_by_id[loop_id])[0]
        if not any(
            ref == (loop_id, LOOP_CURRENT_ITEM)
            for step in steps
            for ref in _step_references(step)
        ):
            raise ValueError(
                f"Loop step {loop_id!r} must have its 'current_item' output "
                "connected to at least one step"
            )
        body_ids = _descendants(loop_id, dependencies)
        if end_step_id not in body_ids:
            raise ValueError(
                f"Loop ending step {end_step_id!r} is not reachable from "
                f"loop {loop_id!r}"
            )
        for body_id in body_ids:
            if _is_loop(steps_by_id[body_id]):
                raise ValueError("Nested loops are not supported")
            if body_id in loop_of:
                raise ValueError(
                    f"Step {body_id!r} cannot belong to more than one loop"
                )
            loop_of[body_id] = loop_id
        loops[loop_id] = LoopInfo(
            loop_id=loop_id,
            end_step_id=end_step_id,
            body=tuple(
                step.step_id for step in order if step.step_id in body_ids
            ),
        )

    # No post-loop continuation: the step ending a loop has no dependents.
    for end_step_id in loop_end_of:
        for step in steps:
            if end_step_id in dependencies[step.step_id]:
                raise ValueError(
                    "Step ending a loop cannot connect to downstream steps"
                )
    return loops, loop_of


def analyze_steps(steps: Sequence[Any]) -> WorkflowGraph:
    """Builds the dependency graph of ``steps``.

    References to unknown steps are ignored here (they fail at run time,
    as before). ``Loop.inputs.loop_ending`` is a back-edge excluded from
    the forward edges; loop subgraphs are validated.

    Raises:
        ValueError: Duplicate step ids, a dependency cycle or an invalid
            loop (see :func:`_analyze_loops`).
    """
    ids = [step.step_id for step in steps]
    duplicates = sorted({step_id for step_id in ids if ids.count(step_id) > 1})
    if duplicates:
        raise ValueError(f"Duplicate step ids: {', '.join(duplicates)}")
    known = set(ids)
    user_input_ids = frozenset(
        step.step_id for step in steps if _is_user_input(step)
    )
    referenced: dict[str, set[str]] = {
        step_id: set() for step_id in ids if step_id not in user_input_ids
    }
    dependencies: dict[str, frozenset[str]] = {}
    for step in steps:
        step_dependencies = set()
        for ref_step, ref_output in _step_references(step):
            if ref_step not in known:
                continue
            step_dependencies.add(ref_step)
            if ref_step not in user_input_ids:
                referenced[ref_step].add(ref_output)
        dependencies[step.step_id] = frozenset(step_dependencies)
    order = _topological_order(steps, dependencies)
    loops, loop_of = _analyze_loops(steps, order, dependencies)
    return WorkflowGraph(
        order=order,
        dependencies=dependencies,
        user_input_ids=user_input_ids,
        referenced_outputs={
            step_id: frozenset(outputs)
            for step_id, outputs in referenced.items()
        },
        loops=loops,
        loop_of=loop_of,
    )


# --- Execution arguments ---------------------------------------------------


def _user_input_names(graph: WorkflowGraph) -> set[str]:
    """User inputs read by the call steps (``${args.<name>}``)."""
    names: set[str] = set()
    for step in graph.call_steps:
        for ref_step, ref_output in _step_references(step):
            if ref_step in graph.user_input_ids:
                names.add(ref_output)
    return names


def required_args(steps: Sequence[Any]) -> list[str]:
    """Execution arguments the generated YAML reads (``${args.<name>}``).

    ``workspace_id`` (sent by every executor call) plus the user inputs
    referenced by the steps. The user's token is not included.
    """
    graph = analyze_steps(steps)
    names = _user_input_names(graph)
    if graph.call_steps:
        names.add("workspace_id")
    return sorted(names)


def missing_required_args(
    steps: Sequence[Any], input_args: Mapping[str, Any] | None
) -> list[str]:
    """Required execution arguments absent (or null) in ``input_args``."""
    args = input_args or {}
    return [name for name in required_args(steps) if args.get(name) is None]


def _completed_outputs(state: Any) -> Mapping[str, Any] | None:
    if isinstance(state, BaseModel):
        state = state.model_dump(mode="json")
    if not isinstance(state, Mapping):
        return None
    if state.get("status") != StepStatusEnum.COMPLETED.value:
        return None
    outputs = state.get("outputs")
    return outputs if isinstance(outputs, Mapping) else None


def build_prior_outputs(
    steps: Sequence[Any], step_states: Mapping[str, Any] | None
) -> dict[str, dict[str, Any]]:
    """Outputs of the completed steps, limited to referenced outputs.

    Every completed top-level call step is included (``{}`` when nothing
    references it) so its gate skips it in the next execution. ``Loop``
    steps and loop body steps are not gated: the ``Loop`` step returns its
    cached snapshot and completed body iterations
    (``"<step_id>#<n>"``) are skipped by the executor's idempotency guard.
    """
    graph = analyze_steps(steps)
    states = step_states or {}
    prior: dict[str, dict[str, Any]] = {}
    for step in graph.top_level_call_steps:
        outputs = _completed_outputs(states.get(step_state_key(step.step_id)))
        if outputs is None:
            continue
        wanted = graph.referenced_outputs.get(step.step_id, frozenset())
        prior[step.step_id] = {
            name: outputs[name] for name in sorted(wanted) if name in outputs
        }
    return prior


def json_size(value: Any) -> int:
    """UTF-8 size of ``value`` serialised as compact JSON."""
    text = json.dumps(
        value, separators=(",", ":"), ensure_ascii=False, default=str
    )
    return len(text.encode("utf-8"))


def prior_outputs_args(
    steps: Sequence[Any],
    step_states: Mapping[str, Any] | None,
    *,
    max_bytes: int = PRIOR_OUTPUTS_ARGS_MAX_BYTES,
) -> dict[str, Any]:
    """Execution arguments that carry completed steps into a new execution.

    ``{"prior_outputs": ...}`` while small enough, else
    ``{"fetch_checkpoint": True}`` so the YAML loads them from the
    checkpoint endpoint. ``{}`` when no step completed yet.
    """
    prior = build_prior_outputs(steps, step_states)
    if not prior:
        return {}
    if json_size(prior) <= max_bytes:
        return {"prior_outputs": prior}
    return {"fetch_checkpoint": True}


# --- YAML generation -------------------------------------------------------


def _field_access(variable: str, name: str) -> str:
    if _IDENTIFIER_RE.match(name):
        return f"${{{variable}.{name}}}"
    return f"${{{variable}[{json.dumps(name)}]}}"


def _resolve_value(value: Any, user_input_ids: frozenset[str]) -> Any:
    """Replaces step output references with YAML expressions.

    User inputs read the execution arguments; other steps read their
    ``<step>_out`` variable (set by the call or by ``prior_outputs``).
    """
    reference = _as_reference(value)
    if reference is not None:
        ref_step, ref_output = reference
        if ref_step in user_input_ids:
            return _field_access("args", ref_output)
        return _field_access(f"{ref_step}_out", ref_output)
    if isinstance(value, Mapping):
        return {
            key: _resolve_value(item, user_input_ids)
            for key, item in value.items()
        }
    if isinstance(value, (list, tuple)):
        return [_resolve_value(item, user_input_ids) for item in value]
    return value


def _validate_step_id(step_id: Any) -> None:
    if isinstance(step_id, str) and ITERATION_SEPARATOR in step_id:
        # '#' separates '<step_id>#<iteration>' step state keys.
        validate_step_id_chars(step_id)
    if (
        not isinstance(step_id, str)
        or len(step_id) > MAX_STEP_ID_LENGTH
        or not _STEP_ID_RE.match(step_id)
    ):
        raise ValueError(
            f"Invalid step id {step_id!r}: use at most {MAX_STEP_ID_LENGTH} "
            "letters, digits or underscores, not starting with a digit."
        )


def _retry_policy() -> dict[str, Any]:
    return {
        "predicate": f"${{{PREDICATE_NAME}}}",
        "max_retries": STEP_MAX_RETRIES,
        "backoff": {
            "initial_delay": STEP_RETRY_INITIAL_DELAY_SECONDS,
            "max_delay": STEP_RETRY_MAX_DELAY_SECONDS,
            "multiplier": STEP_RETRY_MULTIPLIER,
        },
    }


def _auth_headers() -> dict[str, str]:
    return {"Authorization": "${args.user_auth_header}"}


def _run_url(suffix: str) -> str:
    return (
        '${executor_url + "/runs/" + text.url_encode(run_id) + '
        f'"/{suffix}"}}'
    )


def _assign_steps(
    name: str, assignments: list[dict[str, Any]]
) -> list[dict[str, Any]]:
    """Splits assignments into steps of at most 50 (GCP limit)."""
    steps = []
    for index in range(0, len(assignments), MAX_ASSIGNMENTS_PER_STEP):
        chunk = assignments[index : index + MAX_ASSIGNMENTS_PER_STEP]
        number = index // MAX_ASSIGNMENTS_PER_STEP + 1
        chunk_name = name if number == 1 else f"{name}_{number}"
        steps.append({chunk_name: {"assign": chunk}})
    return steps


def _switch(
    name: str,
    condition: str,
    target: dict[str, Any],
    *,
    default_next: str | None = None,
) -> dict[str, Any]:
    """One-condition ``switch`` step (``target``: ``next`` / ``return``)."""
    spec: dict[str, Any] = {"switch": [{"condition": condition, **target}]}
    if default_next is not None:
        spec["next"] = default_next
    return {name: spec}


def _callback_step(
    name: str, body: dict[str, Any], failed_step: str
) -> dict[str, Any]:
    """``POST /runs/{run_id}/finished``; failures are swallowed."""
    return {
        name: {
            "try": {
                "call": "http.post",
                "args": {
                    "url": _run_url("finished"),
                    "headers": _auth_headers(),
                    "body": body,
                    "timeout": CALLBACK_TIMEOUT_SECONDS,
                },
            },
            "retry": _retry_policy(),
            "except": {
                "as": "callback_error",
                "steps": [
                    {failed_step: {"assign": [{"callback_failed": True}]}},
                ],
            },
        },
    }


def _checkpoint_steps(first_gate: str) -> list[dict[str, Any]]:
    """Loads ``prior`` from the checkpoint endpoint when asked to."""
    return [
        _switch(
            "checkpoint_gate",
            _FETCH_CHECKPOINT_EXPR,
            {"next": "load_checkpoint"},
            default_next="prior_gate",
        ),
        {
            "load_checkpoint": {
                "try": {
                    "call": "http.get",
                    "args": {
                        "url": _run_url("checkpoint"),
                        "headers": _auth_headers(),
                        "query": {"execution_id": "${exec_id}"},
                        "timeout": CALLBACK_TIMEOUT_SECONDS,
                    },
                    "result": "checkpoint",
                },
                "retry": _retry_policy(),
            },
        },
        {
            "save_checkpoint": {
                "assign": [
                    {"prior": _CHECKPOINT_PRIOR_EXPR},
                    {"checkpoint": None},
                ],
            },
        },
        # No (valid) prior outputs: every step runs.
        _switch(
            "prior_gate",
            '${get_type(prior) != "map"}',
            {"next": first_gate},
        ),
    ]


def _http_call_step(
    name: str,
    url: str,
    body: dict[str, Any],
    step_timeout_seconds: int,
) -> dict[str, Any]:
    """Retried ``http.post`` executor call storing ``<name>_result``."""
    return {
        name: {
            "try": {
                "call": "http.post",
                "args": {
                    "url": url,
                    "headers": _auth_headers(),
                    "body": body,
                    "timeout": step_timeout_seconds,
                },
                "result": f"{name}_result",
            },
            "retry": _retry_policy(),
        },
    }


def _call_steps(
    step: Any,
    next_gate: str | None,
    *,
    base_url: str,
    step_timeout_seconds: int,
    user_input_ids: frozenset[str],
    loop_id: str | None = None,
) -> list[dict[str, Any]]:
    """Gate, marker, retried executor call and output save of one step.

    Loop body steps (``loop_id`` set) have no gate: their ``<step>_out``
    holds the previous iteration's outputs. They send ``iteration`` so the
    executor checkpoints ``"<step_id>#<iteration>"``, and mark
    ``current_step`` with that key for the failure callback.
    """
    step_id = step.step_id
    body: dict[str, Any] = {
        "run_id": "${run_id}",
        "step_id": step_id,
        "execution_id": "${exec_id}",
        # Dynamically injected from the workspace passed at execution.
        "workspace_id": "${args.workspace_id}",
        "inputs": {
            name: _resolve_value(value, user_input_ids)
            for name, value in _dump_model(step.inputs).items()
        },
        "config": _dump_model(step.settings),
    }
    steps: list[dict[str, Any]] = []
    if loop_id is None:
        # Skips the step when its output is already known (resume).
        steps.append(
            _switch(
                f"{step_id}_gate",
                f"${{{step_id}_out != null}}",
                {"next": next_gate},
            )
        )
        marker: str = step_id
    else:
        body["iteration"] = f"${{{loop_id}_idx}}"
        marker = (
            f'${{"{step_id}{ITERATION_SEPARATOR}" + string({loop_id}_idx)}}'
        )
    step_type = NodeTypes(step.type).value.lower()
    steps += [
        {f"{step_id}_mark": {"assign": [{"current_step": marker}]}},
        _http_call_step(
            step_id, f"{base_url}/{step_type}", body, step_timeout_seconds
        ),
        {
            f"{step_id}_save": {
                "assign": [{f"{step_id}_out": f"${{{step_id}_result.body}}"}],
            },
        },
    ]
    return steps


def _linked_loop_entry(entry: Any, user_input_ids: frozenset[str]) -> Any:
    """One ``linked_items`` value of a Linked Items ``Loop`` call.

    A wire becomes its ``${...}`` expression. A Media Gallery pick stays a
    literal holding only the ids the executor reads (``sourceMediaItem``
    ``mediaItemId`` / ``mediaIndex``, ``sourceAssetId``): signed preview
    URLs would bloat the YAML, and free-form strings (``role``) could be
    evaluated as workflow expressions.
    """
    if _as_reference(entry) is not None or not isinstance(entry, Mapping):
        return _resolve_value(entry, user_input_ids)
    pick: dict[str, Any] = {}
    source_media_item = entry.get("sourceMediaItem")
    if isinstance(source_media_item, Mapping):
        pick["sourceMediaItem"] = {
            key: source_media_item[key]
            for key in ("mediaItemId", "mediaIndex")
            if source_media_item.get(key) is not None
        }
    source_asset_id = entry.get("sourceAssetId")
    if source_asset_id is not None or not pick:
        # An id-less pick stays non-empty so the executor rejects it
        # instead of skipping it like an empty upstream output.
        pick["sourceAssetId"] = source_asset_id
    return pick


def _loop_steps(
    loop_step: Any,
    body_steps: Sequence[Any],
    *,
    base_url: str,
    step_timeout_seconds: int,
    user_input_ids: frozenset[str],
) -> list[dict[str, Any]]:
    """``/resolve-loop-items`` call and ``for`` loop of one ``Loop`` step.

    The ``Loop`` step is never gated: on resume ``/resolve-loop-items``
    returns its cached snapshot. Only the inputs of the configured mode are
    sent: ``items_text`` in text mode, the ``linked_items`` list in Linked
    Items mode (one expression per wire and one literal per Media Gallery
    pick, in insertion order). A source that resolves to zero items fails
    the resolver call, so the ``for`` loop is never reached. Each iteration
    exposes ``<loop>_out.current_item`` to the body steps, which overwrite
    their ``<step>_out`` (O(1) memory).
    """
    loop_id = loop_step.step_id
    settings = _dump_model(loop_step.settings)
    raw_inputs = _dump_model(loop_step.inputs)
    mode = settings.get("mode")
    inputs: dict[str, Any] = {}
    if mode == "text_input":
        inputs["items_text"] = _resolve_value(
            raw_inputs.get("items_text"), user_input_ids
        )
    elif mode == "linked_items":
        linked = raw_inputs.get("linked_items")
        if not isinstance(linked, list):
            linked = [] if linked is None else [linked]
        inputs["linked_items"] = [
            _linked_loop_entry(entry, user_input_ids) for entry in linked
        ]
    body = {
        "run_id": "${run_id}",
        "step_id": loop_id,
        "execution_id": "${exec_id}",
        "workspace_id": "${args.workspace_id}",
        "inputs": inputs,
        "config": settings,
    }
    iteration_steps: list[dict[str, Any]] = [
        {
            f"{loop_id}_iter": {
                "assign": [
                    {
                        f"{loop_id}_out": {
                            LOOP_CURRENT_ITEM: f"${{{loop_id}_item}}"
                        }
                    }
                ],
            },
        },
    ]
    for step in body_steps:
        iteration_steps += _call_steps(
            step,
            None,
            base_url=base_url,
            step_timeout_seconds=step_timeout_seconds,
            user_input_ids=user_input_ids,
            loop_id=loop_id,
        )
    return [
        {f"{loop_id}_mark": {"assign": [{"current_step": loop_id}]}},
        _http_call_step(
            loop_id,
            f"{base_url}/{RESOLVE_LOOP_ITEMS_PATH}",
            body,
            step_timeout_seconds,
        ),
        {
            f"{loop_id}_save": {
                "assign": [
                    {f"{loop_id}_items": f"${{{loop_id}_result.body.items}}"},
                    {f"{loop_id}_result": None},
                ],
            },
        },
        {
            f"{loop_id}_loop": {
                "for": {
                    "value": f"{loop_id}_item",
                    "index": f"{loop_id}_idx",
                    "in": f"${{{loop_id}_items}}",
                    "steps": iteration_steps,
                },
            },
        },
    ]


def _is_transient_subworkflow() -> dict[str, Any]:
    """Retry predicate: network errors, timeouts, 429 and 5xx.

    Errors whose body says ``retry_safe: false`` (the executor could not
    rule out a duplicate generation) are never retried. Fields of ``e`` are
    type-checked before use: the predicate must never raise.
    """
    tags = " or ".join(f'"{tag}" in tags' for tag in TRANSIENT_ERROR_TAGS)
    codes = " or ".join(f"code == {code}" for code in TRANSIENT_HTTP_CODES)
    http_error = f'${{"HttpError" in tags and ({codes})}}'
    return {
        "params": ["e"],
        "steps": [
            _switch(
                "check_error_type",
                '${get_type(e) != "map"}',
                {"return": False},
            ),
            {"init_fields": {"assign": [{"tags": []}, {"code": 0}]}},
            _switch(
                "tags_gate",
                '${get_type(map.get(e, "tags")) != "list"}',
                {"next": "code_gate"},
            ),
            {"read_tags": {"assign": [{"tags": "${e.tags}"}]}},
            _switch(
                "code_gate",
                '${get_type(map.get(e, "code")) != "integer"}',
                {"next": "body_gate"},
            ),
            {"read_code": {"assign": [{"code": "${e.code}"}]}},
            _switch(
                "body_gate",
                '${get_type(map.get(e, "body")) != "map"}',
                {"next": "check_tags"},
            ),
            _switch(
                "check_retry_safe", _NOT_RETRY_SAFE_EXPR, {"return": False}
            ),
            {
                "check_tags": {
                    "switch": [
                        {"condition": f"${{{tags}}}", "return": True},
                        {"condition": http_error, "return": True},
                    ],
                },
            },
            {"not_transient": {"return": False}},
        ],
    }


def _step_names(steps: list[dict[str, Any]]) -> Iterator[str]:
    for step in steps:
        for name, spec in step.items():
            yield name
            for block in (spec.get("try"), spec.get("except"), spec.get("for")):
                if isinstance(block, Mapping) and "steps" in block:
                    yield from _step_names(block["steps"])


def _check_unique_step_names(steps: list[dict[str, Any]]) -> None:
    names = list(_step_names(steps))
    clashes = sorted({name for name in names if names.count(name) > 1})
    if clashes:
        raise ValueError(
            "Step ids clash with generated workflow step names: "
            + ", ".join(clashes)
        )


def _validate_timeout(step_timeout_seconds: Any) -> None:
    if (
        not isinstance(step_timeout_seconds, int)
        or isinstance(step_timeout_seconds, bool)
        or not 1 <= step_timeout_seconds <= MAX_HTTP_TIMEOUT_SECONDS
    ):
        raise ValueError(
            f"Invalid step timeout {step_timeout_seconds!r}: use 1 to "
            f"{MAX_HTTP_TIMEOUT_SECONDS} seconds."
        )


def build_workflow_definition(
    steps: Sequence[Any],
    *,
    executor_url: str,
    step_timeout_seconds: int = 300,
) -> dict[str, Any]:
    """GCP Workflows definition (as a dict) of the given workflow steps.

    Top-level call steps run first (gated by ``prior_outputs``), then each
    ``Loop`` step with its body inside a ``for`` loop. Steps outside a loop
    never depend on a loop or its body (no post-loop continuation), so
    this order respects every data dependency.

    Raises:
        ValueError: Invalid or clashing step ids, duplicates, a cycle, an
            invalid loop, user inputs named like a reserved argument or an
            invalid timeout.
    """
    _validate_timeout(step_timeout_seconds)
    graph = analyze_steps(steps)
    call_steps = graph.call_steps
    for step in call_steps:
        _validate_step_id(step.step_id)
    reserved = sorted(_user_input_names(graph) & RESERVED_ARGS)
    if reserved:
        raise ValueError(
            "User input names are reserved: " + ", ".join(reserved)
        )
    base_url = executor_url.rstrip("/")
    call_ids = [step.step_id for step in call_steps]
    top_level = graph.top_level_call_steps
    top_level_ids = [step.step_id for step in top_level]
    loop_steps = [step for step in call_steps if step.step_id in graph.loops]
    steps_by_id = {step.step_id: step for step in call_steps}
    # Entry step of each block: top-level gates, then loop markers.
    gates = (
        [f"{step_id}_gate" for step_id in top_level_ids]
        + [f"{step.step_id}_mark" for step in loop_steps]
        + ["steps_done"]
    )

    init = _assign_steps(
        "init",
        [
            {"executor_url": base_url},
            {"run_id": _RUN_ID_EXPR},
            {"exec_id": _EXECUTION_ID_EXPR},
            {"prior": _PRIOR_ARGS_EXPR},
            {"checkpoint": None},
            {"current_step": ""},
            {"callback_failed": False},
            # Declared here so they are visible outside the try block.
            *({f"{step_id}_out": None} for step_id in call_ids),
            *({f"{step.step_id}_items": None} for step in loop_steps),
        ],
    )
    run_steps: list[dict[str, Any]] = _checkpoint_steps(gates[0])
    run_steps += _assign_steps(
        "init_outputs",
        [
            *(
                {f"{step_id}_out": f'${{map.get(prior, "{step_id}")}}'}
                for step_id in top_level_ids
            ),
            {"prior": None},
        ],
    )
    for index, step in enumerate(top_level):
        run_steps += _call_steps(
            step,
            gates[index + 1],
            base_url=base_url,
            step_timeout_seconds=step_timeout_seconds,
            user_input_ids=graph.user_input_ids,
        )
    for step in loop_steps:
        run_steps += _loop_steps(
            step,
            [
                steps_by_id[body_id]
                for body_id in graph.loops[step.step_id].body
            ],
            base_url=base_url,
            step_timeout_seconds=step_timeout_seconds,
            user_input_ids=graph.user_input_ids,
        )
    run_steps.append({"steps_done": {"assign": [{"current_step": ""}]}})

    failure_steps = [
        # Executions without run_id have no run to report to.
        _switch("failure_gate", _NO_RUN_ID_EXPR, {"next": "reraise"}),
        _callback_step(
            "report_failure",
            {
                "execution_id": "${exec_id}",
                "status": "FAILED",
                "step_id": "${current_step}",
                "error": "${e}",
            },
            "failure_callback_failed",
        ),
        {"reraise": {"raise": "${e}"}},
    ]
    main_steps = [
        *init,
        {
            "run_steps": {
                "try": {"steps": run_steps},
                "except": {"as": "e", "steps": failure_steps},
            },
        },
        _switch("success_gate", _NO_RUN_ID_EXPR, {"next": "done"}),
        _callback_step(
            "report_success",
            {"execution_id": "${exec_id}", "status": "SUCCEEDED"},
            "success_callback_failed",
        ),
        {
            "done": {
                "return": {
                    step_id: f"${{{step_id}_out}}" for step_id in call_ids
                },
            },
        },
    ]
    _check_unique_step_names(main_steps)
    return {
        "main": {"params": ["args"], "steps": main_steps},
        PREDICATE_NAME: _is_transient_subworkflow(),
    }


def build_workflow_yaml(
    steps: Sequence[Any],
    *,
    executor_url: str,
    step_timeout_seconds: int = 300,
) -> str:
    """GCP Workflows YAML source of the given workflow steps.

    The source starts with :data:`YAML_HEADER`.

    Raises:
        ValueError: Invalid definition (see
            :func:`build_workflow_definition`) or YAML above the GCP
            source size limit.
    """
    definition = build_workflow_definition(
        steps,
        executor_url=executor_url,
        step_timeout_seconds=step_timeout_seconds,
    )
    source = YAML_HEADER + yaml.dump(
        definition,
        Dumper=_NoAliasDumper,
        sort_keys=False,
        indent=2,
        default_flow_style=False,
        # Keeps each expression on one line (readable in the GCP console).
        width=_YAML_LINE_WIDTH,
    )
    if len(source.encode("utf-8")) > MAX_SOURCE_BYTES:
        raise ValueError(
            "The workflow is too large to deploy "
            f"(GCP limit {MAX_SOURCE_BYTES // 1024} KB)."
        )
    return source


# --- Definition hashing & resume step invalidation ---


def _step_canonical_payload(step: Any) -> dict[str, Any]:
    if isinstance(step, Mapping):
        try:
            step = WorkflowBase.model_validate(
                {"name": "wf", "steps": [step]}
            ).steps[0]
        except Exception:  # pylint: disable=broad-exception-caught
            pass
    if isinstance(step, Mapping):
        step_type = step.get("type")
        inputs = step.get("inputs")
        config = (
            step.get("config") if "config" in step else step.get("settings")
        )
    else:
        step_type = getattr(step, "type", None)
        inputs = getattr(step, "inputs", None)
        config = getattr(step, "config", None)
        if config is None:
            config = getattr(step, "settings", None)
    type_str = (
        step_type.value if hasattr(step_type, "value") else str(step_type or "")
    )
    return {
        "type": type_str,
        "inputs": _dump_model(inputs),
        "config": _dump_model(config),
    }


def compute_step_hash(step: Any) -> str:
    """SHA-256 hex digest of canonical ``{type, inputs, config}``."""
    canonical = json.dumps(
        _step_canonical_payload(step),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        default=str,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def compute_definition_hash(steps: Sequence[Any]) -> str:
    """SHA-256 hex digest of canonical ``workflow.steps`` (excluding UI fields)."""
    payload = [
        {
            "step_id": (
                step.get("step_id")
                if isinstance(step, Mapping)
                else step.step_id
            ),
            **_step_canonical_payload(step),
        }
        for step in steps
    ]
    canonical = json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        default=str,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def initial_step_states(steps: Sequence[Any]) -> dict[str, dict[str, Any]]:
    """Initial ``step_states`` mapping with per-step ``definition_hash``.

    Loop body steps get no placeholder: their per-iteration records
    (``"<step_id>#<n>"``) are created lazily by the idempotency guard.
    """
    graph = analyze_steps(steps)
    return {
        step_state_key(step.step_id): {
            "status": StepStatusEnum.PENDING.value,
            "attempts": 0,
            "in_progress_continuations": 0,
            "definition_hash": compute_step_hash(step),
        }
        for step in graph.call_steps
        if step.step_id not in graph.loop_of
    }


def _transitive_descendants(
    graph: WorkflowGraph, seed_step_ids: Iterable[str]
) -> set[str]:
    """Returns ``seed_step_ids`` plus every step that transitively depends on them."""
    dependents: dict[str, set[str]] = {
        step.step_id: set() for step in graph.order
    }
    for step_id, deps in graph.dependencies.items():
        for dep in deps:
            if dep in dependents:
                dependents[dep].add(step_id)

    invalidated: set[str] = set()
    queue = [step_id for step_id in seed_step_ids if step_id in dependents]
    while queue:
        current = queue.pop(0)
        if current in invalidated:
            continue
        invalidated.add(current)
        for child in dependents.get(current, ()):
            if child not in invalidated:
                queue.append(child)
    return invalidated


def steps_depending_on_inputs(
    steps: Sequence[Any], changed_input_names: Iterable[str]
) -> set[str]:
    """Call steps that depend directly or transitively on ``changed_input_names``."""
    wanted = set(changed_input_names)
    if not wanted:
        return set()
    graph = analyze_steps(steps)
    direct: set[str] = set()
    for step in graph.call_steps:
        for ref_step, ref_output in _step_references(step):
            if ref_step in graph.user_input_ids and ref_output in wanted:
                direct.add(step.step_id)
    return _transitive_descendants(graph, direct)


def reconcile_step_states_for_resume(
    steps: Sequence[Any],
    existing_states: Mapping[str, Any] | None,
    *,
    run_definition_hash: str | None,
    changed_input_names: Iterable[str] = (),
    previous_steps: Sequence[Any] | None = None,
    run_last_error_category: Any = None,
) -> tuple[dict[str, dict[str, Any]], str | None]:
    """Reconciles ``step_states`` for ``resume``.

    Rules:
    * If ``run_definition_hash`` is ``None`` (or a completed step has ``None``
      or mismatched ``definition_hash``), that step and its descendants are
      invalidated.
    * Any step that depends directly or transitively on ``changed_input_names``
      is invalidated.
    * Completed steps that are not invalidated are kept (with their
      ``definition_hash`` refreshed).
    * A non-invalidated failed step with ``job_id`` and ``CAP_EXCEEDED`` keeps
      its ``job_id`` (resetting ``attempts = 0`` and ``first_started_at = None``)
      so the resumed execution re-polls the long-running job before regenerating.
    * All other steps are reset to ``PENDING`` with ``attempts = 0`` and the
      current ``definition_hash``.
    * Returns ``(reconciled_step_states, first_incomplete_step_id)``.
    """
    graph = analyze_steps(steps)
    states = existing_states or {}
    step_hashes = {
        step.step_id: compute_step_hash(step) for step in graph.call_steps
    }
    prev_step_hashes: dict[str, str] = {}
    if previous_steps:
        for prev in previous_steps:
            prev_id = (
                prev.get("step_id")
                if isinstance(prev, Mapping)
                else getattr(prev, "step_id", None)
            )
            if prev_id:
                prev_step_hashes[str(prev_id)] = compute_step_hash(prev)

    grouped = group_step_states(states)
    changed_seeds: set[str] = set()
    if run_definition_hash is None:
        changed_seeds.update(step.step_id for step in graph.call_steps)
    else:
        for step in graph.call_steps:
            # Body steps only have "<step_id>#<n>" iteration records.
            stored_hash = next(
                (
                    _state_dict(raw_state).get("definition_hash")
                    for _, raw_state in grouped.get(step.step_id, [])
                    if _state_dict(raw_state).get("definition_hash")
                ),
                None,
            )
            if stored_hash is None:
                stored_hash = prev_step_hashes.get(step.step_id)
            if stored_hash is None or stored_hash != step_hashes[step.step_id]:
                changed_seeds.add(step.step_id)

    invalidated = _transitive_descendants(graph, changed_seeds)
    invalidated |= steps_depending_on_inputs(steps, changed_input_names)

    reconciled: dict[str, dict[str, Any]] = {}
    first_incomplete: str | None = None
    run_err_str = (
        run_last_error_category.value
        if hasattr(run_last_error_category, "value")
        else str(run_last_error_category or "")
    )

    for step in graph.call_steps:
        step_id = step.step_id
        current_hash = step_hashes[step_id]
        is_invalidated = step_id in invalidated
        if step_id in graph.loop_of:
            # Body iterations are created lazily: keep the completed ones
            # (and re-pollable CAP_EXCEEDED jobs), drop the others.
            completed_count = 0
            all_completed = True
            for iteration, raw_state in grouped.get(step_id, []):
                if iteration is None:
                    continue
                record, completed = _reconcile_record(
                    _state_dict(raw_state),
                    is_invalidated=is_invalidated,
                    current_hash=current_hash,
                    run_err_str=run_err_str,
                )
                completed_count += int(completed)
                all_completed = all_completed and completed
                if completed or record.get("job_id") is not None:
                    reconciled[step_state_key(step_id, iteration)] = record
            expected = _total_iterations(reconciled.get(graph.loop_of[step_id]))
            if first_incomplete is None and (
                not all_completed
                or expected is None
                or completed_count < expected
            ):
                first_incomplete = step_id
            continue

        record, completed = _reconcile_record(
            _state_dict(states.get(step_state_key(step_id))),
            is_invalidated=is_invalidated,
            current_hash=current_hash,
            run_err_str=run_err_str,
        )
        reconciled[step_id] = record
        if not completed and first_incomplete is None:
            first_incomplete = step_id

    return reconciled, first_incomplete


def _state_dict(raw_state: Any) -> dict[str, Any]:
    if isinstance(raw_state, BaseModel):
        return dict(raw_state.model_dump(mode="json", exclude_none=True))
    if isinstance(raw_state, Mapping):
        return dict(raw_state)
    return {}


def _total_iterations(loop_state: Mapping[str, Any] | None) -> int | None:
    """``total_iterations`` of a completed ``Loop`` record, else ``None``."""
    if not loop_state:
        return None
    outputs = _completed_outputs(loop_state)
    total = outputs.get("total_iterations") if outputs else None
    return total if isinstance(total, int) else None


def _reconcile_record(
    state_dict: dict[str, Any],
    *,
    is_invalidated: bool,
    current_hash: str,
    run_err_str: str,
) -> tuple[dict[str, Any], bool]:
    """Resume state of one ``step_states`` record and whether it is kept
    as completed."""
    is_completed = state_dict.get(
        "status"
    ) == StepStatusEnum.COMPLETED.value and isinstance(
        state_dict.get("outputs"), Mapping
    )
    if is_completed and not is_invalidated:
        state_dict["definition_hash"] = current_hash
        state_dict.pop("error", None)
        return state_dict, True

    error_info = state_dict.get("error") or state_dict.get("last_error")
    error_cat = (
        error_info.get("category") if isinstance(error_info, Mapping) else None
    )
    record: dict[str, Any] = {
        "status": StepStatusEnum.PENDING.value,
        "attempts": 0,
        "in_progress_continuations": 0,
        "definition_hash": current_hash,
    }
    if (
        not is_invalidated
        and state_dict.get("job_id") is not None
        and (error_cat == "CAP_EXCEEDED" or run_err_str == "CAP_EXCEEDED")
    ):
        record = {"status": record["status"], "job_id": state_dict["job_id"]}
        record.update(
            attempts=0,
            in_progress_continuations=0,
            definition_hash=current_hash,
        )
    return record, False
